# Generated by Django 5.2.7 on 2026-01-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_alumno', models.CharField(blank=True, max_length=20, null=True)),
                ('info_escolar', models.CharField(blank=True, max_length=255, null=True)),
                ('info_salud', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Alumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'Nivel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('id_padrino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Padrino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id_parroquia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parroquia', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_secretaria', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Parroquia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'Periodo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Representante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sacramento',
            fields=[
                ('id_sacramento', models.AutoField(primary_key=True, serialize=False)),
                ('id_nivel_requisito', models.IntegerField(blank=True, null=True)),
                ('nombre_sacramento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Sacramento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('estado_inscripcion', models.CharField(max_length=50)),
                ('estado_aprobacion', models.CharField(max_length=50)),
                ('comentarios_excepcion', models.CharField(blank=True, max_length=500, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.alumno')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.grupo')),
            ],
            options={
                'db_table': 'Inscripcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sesion', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('inscripcion_id_inscripcion', models.ForeignKey(db_column='Inscripcion_id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.inscripcion')),
            ],
            options={
                'db_table': 'Asistencia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_nivel',
            field=models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.nivel'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_parroquia',
            field=models.ForeignKey(db_column='id_parroquia', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.parroquia'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_periodo',
            field=models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.periodo'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='sacramento_id_sacramento',
            field=models.ForeignKey(db_column='Sacramento_id_sacramento', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.sacramento'),
        ),
        migrations.CreateModel(
            name='SacramentoRealizado',
            fields=[
                ('id_alumno_sacramento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_realizacion', models.DateField()),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.alumno')),
                ('id_inscripcion_prep', models.ForeignKey(blank=True, db_column='id_inscripcion_prep', null=True, on_delete=django.db.models.deletion.SET_NULL, to='DjangoCatequesis.inscripcion')),
                ('id_sacramento', models.ForeignKey(db_column='id_sacramento', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.sacramento')),
            ],
            options={
                'db_table': 'Sacramento_realizado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('id_catequista', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('esta_activo', models.BooleanField()),
                ('id_parroquia', models.ForeignKey(db_column='id_parroquia', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.parroquia')),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.perfil')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_carga', models.DateField()),
                ('referencia_storage', models.CharField(blank=True, max_length=255, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.alumno')),
                ('id_usuario_carga', models.ForeignKey(db_column='id_usuario_carga', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.usuario')),
            ],
            options={
                'db_table': 'Documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Catequista',
            fields=[
                ('id_catequista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('es_joven_apoyo', models.BooleanField()),
                ('usuario_id_user', models.ForeignKey(db_column='Usuario_id_user', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.usuario')),
            ],
            options={
                'db_table': 'Catequista',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrupoCatequista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catequista_id_catequista', models.ForeignKey(db_column='Catequista_id_catequista', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.catequista')),
                ('grupo_id_grupo', models.ForeignKey(db_column='Grupo_id_grupo', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.grupo')),
            ],
            options={
                'db_table': 'Grupo-Catequista',
                'managed': True,
                'unique_together': {('grupo_id_grupo', 'catequista_id_catequista')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionPadrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion_id_inscripcion', models.ForeignKey(db_column='Inscripcion_id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.inscripcion')),
                ('padrino_id_padrino', models.ForeignKey(db_column='Padrino_id_padrino', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.padrino')),
            ],
            options={
                'db_table': 'Inscripcion-Padrino',
                'managed': True,
                'unique_together': {('padrino_id_padrino', 'inscripcion_id_inscripcion')},
            },
        ),
        migrations.CreateModel(
            name='RepresentanteAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id_alumno', models.ForeignKey(db_column='Alumno_id_alumno', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.alumno')),
                ('representante_id_representante', models.ForeignKey(db_column='Representante_id_representante', on_delete=django.db.models.deletion.CASCADE, to='DjangoCatequesis.representante')),
            ],
            options={
                'db_table': 'Representante-Alumno',
                'managed': True,
                'unique_together': {('representante_id_representante', 'alumno_id_alumno')},
            },
        ),
    ]
