# Generated by Django 5.2.7 on 2026-01-12 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoCatequesis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representantealumno',
            name='id',
        ),
        migrations.AlterField(
            model_name='representantealumno',
            name='representante_id_representante',
            field=models.ForeignKey(db_column='Representante_id_representante', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DjangoCatequesis.representante'),
        ),
    ]
